### ISSUE TITLE
Fehler: Doppelte Zuordnung von Personen

### ISSUE THREAD

**Issue by GerryUni** [phoeuia/prse#154]
Reproduktion: Wähle ein Projekt --> bearbeiten --> teile schon zugeteilte Person nochmals zu --> funktioniert (dürfte nicht sein) --> möchte man sie nochmals zuweisen --> Fehlermeldung
Vermutung: Es wird nur die Liste abgeglichen die nach Programmstart erstellt wird.

**Comment by MAschi91** [comment]
#248 by MAschi91 fixed
