### ISSUE TITLE
Button nicht klickbar

### ISSUE THREAD

**Issue by ThoEJ** [phoeuia/prse#214]
Zu Beginn, wenn das Programm die tabellarische Ansicht geladen hat, ist der Button Hinzufügen nicht auswählbar. Dasselbe gilt für den Hinzufügen-Button immer ganz rechts, wenn man die Ansicht erweitert indem man z.B.: ein Projekt auswählt.

**Comment by MAschi91** [comment]
Erfolgreich behoben!
